services:
  php:
    build:
      context: .
      target: test
    volumes:
      - .:/app
      - /app/vendor
      - /app/packages/core/vendor
      - /app/packages/talk/vendor
      - /app/packages/post/vendor
