name: PHP SDK Tests

on:
  push:
    branches: [main]
    paths:
      - 'php/**'
      - '.github/workflows/php.yml'
  pull_request:
    paths:
      - 'php/**'
      - '.github/workflows/php.yml'

defaults:
  run:
    working-directory: php

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and start container
        run: docker compose up -d --build

      - name: Run tests
        run: docker compose exec php ./vendor/bin/phpunit

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and start container
        run: docker compose up -d --build

      - name: Run phpstan
        run: docker compose exec php ./vendor/bin/phpstan
